---
openapi:
    title: Test API for AsyncOpenAI
    description: |
        This is a test app you can use to build your own custom
        openai-based tool. Don't forget to edit your `settings.yaml`.
    version: 0.0.1
        
handler:
    asynchronous: true
    model: gpt-3.5-turbo
    system_prompt_template: |
        You are a math solver.
        Do not add any explanation.
        Please reply using the following JSON format ONLY: {output_schema}
        Always follow this JSON schema, otherwise the execution will fail.
